#机器人几何参，如果机器人是圆形，设置 robot_radius,如果是其他形状设置 footprint
#robot_radius: 0.32 #圆形
footprint: [ [ -0.25, -0.25 ], [ -0.25, 0.25 ], [ 0.25, 0.25 ], [ 0.25, -0.25 ] ] #其他形状

obstacle_range: 2.5 # 用于障碍物探测，比如: 值为 3.0，意味着检测到距离小于 3 米的障碍物时，就会引入代价地图
raytrace_range: 6.0 # 用于清除障碍物，比如：值为 3.5，意味着清除代价地图中 3.5 米以外的障碍物

#膨胀半径，扩展在碰撞区域以外的代价区域，使得机器人规划路径避开障碍物
inflation_radius: 0.5

update_frequency: 5.0 #代价地图更新频率
publish_frequency: 1.0 #发布可视化信息的频率
transform_tolerance: 0.5 #等待坐标变换发布信息的超时时间

#地图类型
map_type: costmap

